### PR TITLE
[MOD-2163] Android: add architectures and add new dist (via 5.0.2.GA)

### LINKED ISSUE #6: App crashes right after launching with this module.
Environment 
- Android API 23(6.0)
- TiSDK 5.0.2.GA
- Android Device : Nexus 5 (6.0)

App crashes right after launching with this module. There is no error message.

### PR DESCRIPTION
**Pull request by yomybaby**
fix #6

### CODE REVIEW

**Comment by ashcoding** [comment]
@yomybaby Reviewed and functionally tested. All okay! Could you update and commit this file https://github.com/appcelerator-modules/ti.compression/blob/e838fcd9a932d975777f5c55eea85a713a926e96/android/documentation/changelog.md as well to reflect the changes?

Once that's updated, this can be merged. :+1:

**Comment by ashcoding** [comment]
Created JIRA ticket for this fix: https://jira.appcelerator.org/browse/MOD-2163

**Comment by yomybaby** [comment]
Thanks. `changeling.md` updated :)

**Comment by ashcoding** [comment]
Thanks! :+1:

**Accepted**

**Pull request merged**
