### PR TITLE
[TIMOB-23594] Android: Recompile ti.compression module against latest SDK

### PR DESCRIPTION
**Pull request by sgtcoolguy**
https://jira.appcelerator.org/browse/TIMOB-23594

### CODE REVIEW

**Comment by sgtcoolguy** [comment]
[ti.compression-android-3.0.0.zip](https://github.com/appcelerator-modules/ti.compression/files/357692/ti.compression-android-3.0.0.zip)

https://github.com/appcelerator-modules/ti.compression/tree/master/android/example

**Comment by sgtcoolguy** [comment]
@ashcoding Not sure why it won't let me assign you to this PR...

**Comment by ashcoding** [comment]
For some weird reason, I seem to not be an admin for this particular repo..

**Comment by ashcoding** [comment]
Works well. Functionally tested.
Please proceed to merge. I don't have the permissions to merge.

**Pull request merged**
